user_dashboard/apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
]

user_dashboard/user_dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^users/', include('apps.dashboard.urls', namespace='dashboard')),
]

user_dashboard/apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from re import match, search
from bcrypt import hashpw, gensalt

class UserManager(models.Manager):
    def register(self, email, first_name, last_name, password, confirm_password, csrfmiddlewaretoken):
        messagelist = []
        # Validate email
        email = email[0]
        if not match(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', email):
            messagelist.append("Invalid email address")
        elif User.objects.filter(email=email):
            messagelist.append("Email Address already in use")
        # Validate first_name
        first_name = first_name[0]
        if len(first_name) < 2:
            messagelist.append("First Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', first_name):
            messagelist.append("First Name must only contain letters")
        # Validate last_name
        last_name = last_name[0]
        if len(last_name) < 2:
            messagelist.append("Last Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', last_name):
            messagelist.append("Last Name must only contain letters")
        # Validate password
        password = password[0]
        if len(password) < 8:
            messagelist.append("Password must be at least 8 characters long")
        # Validate conf_password
        conf_password = confirm_password[0]
        if conf_password != password:
            messagelist.append("Password does not match")
        # Check if all validation checks passed
        if len(messagelist) == 0:
            pw_hash = hashpw(password.encode(), gensalt())
            # Make first registered user an admin
            if User.objects.all():
                new_user = User.objects.create(email=email, first_name=first_name, last_name=last_name, password=pw_hash)
            else:
                new_user = User.objects.create(email=email, first_name=first_name, last_name=last_name, password=pw_hash, user_level = 'admin')
            return (True, new_user.id)
        else:
            return (False, messagelist)
    def login(self, email, password):
        if User.objects.filter(email=email):
            user = User.objects.get(email=email)
            if hashpw(password.encode(), user.password.encode()) == user.password:
                return (True, user.id)
            else:
                return (False, "Invalid password")
        else:
            return (False, "Invalid email address")

    def editInfo(self, user_id, email, first_name, last_name, csrfmiddlewaretoken, user_level=['user']):
        messageList = []
        #Validate email
        email = email[0]
        if not match(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', email):
            messagelist.append("Invalid email address")
        # Validate first_name
        first_name = first_name[0]
        if len(first_name) < 2:
            messagelist.append("First Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', first_name):
            messagelist.append("First Name must only contain letters")
        # Validate last_name
        last_name = last_name[0]
        if len(last_name) < 2:
            messagelist.append("Last Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', last_name):
            messagelist.append("Last Name must only contain letters")
        
        user_level = user_level[0]
        #validations
        if len(messageList) > 0:
            return (False, messageList)

        self.filter(id=user_id).update(email=email, first_name=first_name, last_name=last_name, user_level=user_level)

        return (True, ["User Info updated successfully"])

    def editPassword(self, user_id, password, confirm_password, csrfmiddlewaretoken):
        messagelist = []
        # Validate password
        password = password[0]
        if len(password) < 8:
            messagelist.append("Password must be at least 8 characters long")
        # Validate conf_password
        conf_password = confirm_password[0]
        if conf_password != password:
            messagelist.append("Password does not match")
        # Check if all validation checks passed
        if len(messagelist) > 0:
            return(False, messagelist)

        pw_hash = hashpw(password.encode(), gensalt())

        self.filter(id=user_id).update(password=pw_hash)

        return (True, ["User Info updated successfully"])

    def editDescription(self, user_id, description):
        #no validations
        self.filter(id=user_id).update(description=str(description))
        return (True, ["Description Successfully Updated"])

class User(models.Model):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    password = models.CharField(max_length=255)
    user_level = models.CharField(
        max_length=5,
        choices=(('user', 'User'), ('admin', 'Admin')),
        default='user')
    description = models.TextField(max_length=400, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    userManager = UserManager()
    objects = models.Manager()

user_dashboard/apps/login/forms.py
from django import forms
from .models import User

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(max_length=45, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=45)
    last_name = forms.CharField(max_length=45)
    password = forms.CharField(max_length=45, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=45, widget=forms.PasswordInput)

user_dashboard/apps/login/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User
from .forms import RegisterForm, LoginForm

# Login and reg at homepage
def index(request):
    request.session.clear()
    context = {
        'regform': RegisterForm,
        'loginform': LoginForm
    }
    return render(request, 'login/index.html', context)

# Submit registration form
def register(request):
    regstatus = User.userManager.register(**request.POST)
    if regstatus[0]:
        request.session['user_id'] = regstatus[1]
        return redirect(reverse('dashboard:index'))
    else:
        for message in regstatus[1]:
            messages.warning(request, message)
        return redirect(reverse('login:index'))

# Submit login form
def login(request):
    loginstatus = User.userManager.login(request.POST['email'], request.POST['password'])
    if loginstatus[0]:
        request.session['user_id'] = loginstatus[1]
        return redirect(reverse('dashboard:index'))
    else:
        messages.warning(request, loginstatus[1])
        return redirect(reverse('login:index'))

user_dashboard/apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Welcome | User Dashboard</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/style.css' %}">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand">USER DASHBOARD</a>
            </div>
            <div class="nav navbar-nav navbar-right">
                <form class="form-inline" action="{% url 'login:login' %}" method="post">
                    {% csrf_token %}
                    {% for input in loginform %}
                        <div class="form-group">
                            {{ input.label_tag }}{{ input }}
                        </div>
                    {% endfor %}
                    <button class="btn btn-default btn-sm" type="submit">Log In</button>
                </form>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div class='container'>
        <div class="description">
            <h2>Welcome to the User Dashboard!</h2>
                <div class="row">
                <div class="col-md-6">
                    <h4> The User Dashboard allows you to stay connected with other members in the community. Sign up now to receive and share the most up-to-date news!</h4>
                </div>
                </div>
                <div class="row">
                <div class="col-md-3">
                <span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>
                <h4> Create </h4>
                </div>
                <div class="col-md-3">
                <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>
                <h4> Retrieve </h4>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                    <h4> Update </h4>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-tint" aria-hidden="true"></span>
                    <h4> Delete </h4>
                </div>
            </div>
        </div>
         {% if messages %}
            <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
         </ul>
         {% endif %}
        <div class="register_space">
            <h4>New User? Register Below!</h4>
            <form action="{% url 'login:register' %}" method="post">
            {% csrf_token %}
                <table class="table_space">
                {{ regform.as_table }}
                </table>
                <button class='btn btn-success btn-md' type='submit'>Register</button>
            </form>
        </div>
    </div>
</body>
</html>