user_dashboard/apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit/(?P<user_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_pw/(?P<user_id>\d+)$', views.edit_pw, name='edit_pw'),  #POST
    url(r'^edit_desc/(?P<user_id>\d+)$', views.edit_desc, name='edit_desc'),  #POST  
    url(r'^edit_info/(?P<user_id>\d+)$', views.edit_info, name='edit_info'),  #POST
    url(r'^remove/(?P<user_id>\d+)$', views.remove_admin, name='remove_admin'),  #POST
    url(r'^new$', views.new_admin, name='new_admin'),
    url(r'^create$', views.create_admin, name='create_admin'),  #POST
    url(r'^show/(?P<user_id>\d+)$', views.show, name='show'),
    url(r'^show/(?P<user_id>\d+)/new$', views.new_message, name="new_message"),  #POST
    url(r'^show/(?P<user_id>\d+)/(?P<message_id>\d+)/new$', views.new_comment, name="new_comment"),  #POST
]

'''
TO BE ADDED:
- user link to delete own message
- user link to delete own comment
'''

user_dashboard/user_dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^users/', include('apps.dashboard.urls', namespace='dashboard')),
]

user_dashboard/apps/dashboard/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User

# Create your models here.
class Message(models.Model):
	message = models.CharField(max_length=1000)
	walluser = models.ForeignKey(User, related_name='userwall')
	messageuser = models.ForeignKey(User, related_name='usermessage')
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

class Comment(models.Model):
	comment = models.CharField(max_length=1000)
	user = models.ForeignKey(User, related_name='usercomment')
	message = models.ForeignKey(Message, related_name='messagecomment')
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

user_dashboard/apps/dashboard/forms.py
from django import forms
from .models import User
from ..login.forms import RegisterForm

class EditForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=45)
	last_name = forms.CharField(max_length=45)

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super(EditForm, self).__init__( *args, **kwargs)
		if user:
			self.fields['email'].initial = user.email
			self.fields['first_name'].initial = user.first_name
			self.fields['last_name'].initial = user.last_name




class EditAdminForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=45)
	last_name = forms.CharField(max_length=45)
	user_level = forms.ChoiceField([('admin', 'admin'), ('user', 'user')])

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super(EditAdminForm, self).__init__( *args, **kwargs)
		if user:
			self.fields['email'].initial = user.email
			self.fields['first_name'].initial = user.first_name
			self.fields['last_name'].initial = user.last_name
			self.fields['user_level'].initial = user.user_level


class EditPasswordForm(forms.Form):
	password = forms.CharField(max_length=45, widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=45, widget=forms.PasswordInput)


class EditDescriptionForm(forms.Form):
	description = forms.CharField(max_length=255, widget=forms.Textarea, label='')

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super(EditDescriptionForm, self).__init__( *args, **kwargs)
		if user:
			self.fields['description'].initial = user.description

user_dashboard/apps/dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.urlresolvers import reverse
from .models import User, Message, Comment
from .forms import RegisterForm, EditForm, EditAdminForm, EditPasswordForm, EditDescriptionForm

# user/admin home page
def index(request):
    if not 'user_id' in request.session: #fast fail to prevent hacking
        return redirect(reverse('login:index'))
    current_user = User.objects.get(id=request.session['user_id'])
    user = User.objects.all()
    context = { 'users': user }
    if current_user.user_level == 'admin':
        return render(request, 'dashboard/index_admin.html', context)
    else: #only two choices for user level - admin and user
        return render(request, 'dashboard/index.html', context)

# users page to edit own info
def edit(request, user_id):
    if not 'user_id' in request.session: #fast fail to prevent hacking 
        return redirect(reverse('login:index'))
    #get the user object for whomever is in session
    user = User.objects.get(id=request.session['user_id'])
    print user_id, type(user_id)
    print user.id, type(user.id)
    #if the user_level is 'user', create the appropiate forms and strings
    if user.id == int(user_id) and user.user_level == 'user':
        editForm = EditForm(user=user)
        editDescriptionForm = EditDescriptionForm(user=user)
        editStr = 'profile'
        title = 'Profile'
        hidden = '' #variable to hide 
    elif user.id != int(user_id) and user.user_level == 'user':
        return redirect(reverse('dashboard:edit', args=[user.id]))
    #if the user_level is 'admin' and he is trying to edit himself
    #then create the appropiate forms and strings
    elif user.user_level == 'admin' and user.id == int(user_id):
        editForm = EditAdminForm(user=user)
        editDescriptionForm = EditDescriptionForm(user=user)
        editStr = 'profile'
        title = 'Profile'
        hidden = ''
    #if the user_level is admin and he is trying to edit someone else
    #then create the appropiate forms and strings
    else:
        user = User.objects.get(id=user_id)
        editForm = EditAdminForm(user=user)
        editDescriptionForm = ''
        editStr = "user #" + str(user_id)
        title = 'User'
        hidden = 'hidden'
    #create editPasswordForm
    editPasswordForm = EditPasswordForm()
    context = {
        'editForm': editForm,
        'editPasswordForm': editPasswordForm,
        'editDescriptionForm': editDescriptionForm,
        'editStr': editStr,
        'title':title,
        'user_id': user_id,
        'hidden': hidden,
    }
    return render(request, 'dashboard/edit.html', context)

# POST request for user editing info
def edit_info(request, user_id):  #POST REQUEST
    editStatus = User.userManager.editInfo(user_id, **request.POST)
    return redirect(reverse('dashboard:index'))

# POST request for user editing password
def edit_pw(request, user_id):  #POST REQUEST
    editStatus = User.userManager.editPassword(user_id, **request.POST)
    return redirect(reverse('dashboard:index'))

# POST request for user editing description
def edit_desc(request, user_id):  #POST REQUEST
    editStatus = User.userManager.editDescription(user_id, request.POST['description'])
    return redirect(reverse('dashboard:index'))

# POST link for delete user link (admin only)
def remove_admin(request, user_id):  #POST REQUEST
    User.objects.get(id= user_id).delete()
    return redirect(reverse('dashboard:index'))

# admin page to create new user
def new_admin(request):
    #if no user in session then redirect to login:index
    if not 'user_id' in request.session:
        return redirect(reverse('login:index'))
    #query the current user and check their user level
    #if not admin, redirect to dashboard:index
    current_user = User.objects.get(id=request.session['user_id'])
    if current_user.user_level == 'user':
        return render(request, 'dashboard/index.html', context)

    context = {'regform': RegisterForm }
    return render(request, 'dashboard/new_admin.html', context)

# POST link for new user form (admin only)
def create_admin(request):
    create_status = User.userManager.register(**request.POST)
    if create_status[0]:
        return redirect(reverse('dashboard:index'))
    else:
        for message in create_status[1]:
            messages.warning(request, message)
        return redirect(reverse('login:new_admin'))

# show user wall
def show(request, user_id):
    #if no user in session then redirect to login:index
    if not 'user_id' in request.session:
        return redirect(reverse('login:index'))

    messages = Message.objects.filter(walluser=user_id).order_by('-created_at')
    comments = Comment.objects.all()
    user = User.objects.get(id=user_id)
    context = {
        'user': user,
        'messages': messages,
        'comments': comments
    }
    return render(request, 'dashboard/show.html', context)
# POST request for adding message
def new_message(request, user_id):  #POST REQUEST
    messageuser = User.objects.get(id=request.session['user_id'])
    walluser = User.objects.get(id=user_id)
    message = request.POST['message']
    Message.objects.create(messageuser=messageuser, walluser=walluser, message=message)
    return redirect(reverse('dashboard:show', args=user_id))

# POST request for adding comment
def new_comment(request, user_id, message_id):  #POST REQUEST
    user = User.objects.get(id=request.session['user_id'])
    message = Message.objects.get(id=message_id)
    comment = request.POST['comment']
    Comment.objects.create(user=user, message=message, comment=comment)
    return redirect(reverse('dashboard:show', args=user_id))

'''
TO BE ADDED:
- class-based views
    ex: class New(View):
            def get(self, request):
                # renders new_admin.html
            def post(self, request):
                # processes POST request from FORM on new_admin.html

- user link to delete own message
- user link to delete own comment
'''

user_dashboard/apps/dashboard/templates/dashboard/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Edit {{title}} | User Dashboard</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'dashboard:show' request.session.user_id %}">PROFILE<span class="sr-only">(current)</span></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'login:index' %}">LOGOFF</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class='container'>
			<div id=editInfoForm>
			<h3 class='edit_info'>Edit Information</h3>
				<form action="{% url 'dashboard:edit_info' user_id %}" method="POST">
					{% csrf_token %}
	                <table class="edit_table">
					{{editForm.as_table}}
	                </table>
					<button id="save_button" type='submit' class='btn btn-success btn-sm'>Save</button>
				</form>
			</div>
			<div id="editPasswordForm">
				<h3 class='edit_info'>Change Password</h3>
					<form action="{% url 'dashboard:edit_pw' user_id %}" method="POST">
						{% csrf_token %}
		                <table>
						{{editPasswordForm.as_table}}
		                </table>
						<button type='submit' class='btn btn-success btn-sm'>Update Password</button>
					</form>
			</div>
			<div {{hidden}} id="editDescritionForm">
				<h3 class='edit_info'>Edit Description</h3>
				<form action="{% url 'dashboard:edit_desc' user_id %}" method="POST">
					{% csrf_token %}
	                <table>
					{{editDescriptionForm.as_table}}
	                </table>
					<button type='submit' class='btn btn-success btn-sm'>Save</button>
				</form>
			</div>
		</div>
</body>
</html>

user_dashboard/apps/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home | User Dashboard</title>
</head>
<body>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    rel="stylesheet"><!-- Optional theme -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    rel="stylesheet"><!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-4'>
                <h3>All Users</h3>
            </div>
            <table class="table table-bordered table-hover table-responsive ">
                <tr class="success">
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created_at</th>
                    <th>User_level</th>
                </tr>
                {% for user in users %} 
                <tr class="primary">
                    <td>{{user.id}}</td>
                    <td><a href="{%url 'dashboard:show' user.id%}">{{user.first_name}} {{user.last_name}}</a></td>
                    <td>{{user.email}}</td>
                    <td>{{user.created_at}}</td>
                    <td>{{user.user_level}}</td>
                </tr>
                {% endfor %} 
            </table>
        </div><!-- end of container -->
    </div>
</body>
</html>

user_dashboard/apps/dashboard/templates/dashboard/index_admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home | User Dashboard</title> {% load staticfiles %}
</head>
<body>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    rel="stylesheet"><!-- Optional theme -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    rel="stylesheet"><!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-6'>
                <h3 class='less_margin'>Manage Users</h3>
            </div>
          <!--   <div class='col-md-2 col-md-offset-1'>
                <form action="{% url 'dashboard:new_admin' %}" class="form-inline" method='post'>
                    {% csrf_token %} <button class='btn btn-success btn-sm'
                    type='submit'>Add New</button>
                </form> -->
            </div>
            <table class="table table-bordered table-hover table-responsive">
                <tr class="success">
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created_at</th>
                    <th>User_level</th>
                    <th>Actions</th>
                </tr>
                {% for user in users %} 
                <tr>
                    <td>{{user.id}}</td>
                    <td><a href="{%url 'dashboard:show' user.id%}">{{user.first_name}} {{user.last_name}}</a></td>
                    <td>{{user.email}}</td>
                    <td>{{user.created_at}}</td>
                    <td>{{user.user_level}}</td>
                    <td>
                        <a href= "{% url 'dashboard:remove_admin' user.id %}">Delete</a>  |  
                        <a href="{% url 'dashboard:edit' user.id %}">Edit</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
              <div class='button_add'>
                <form action="{% url 'dashboard:new_admin' %}"  method='post'>
                    {% csrf_token %} 
                    <button class='btn btn-success btn-md' type='submit'>Add New</button>
                </form>
        </div><!-- end of container -->
    </div>
</body>
</html>

user_dashboard/apps/dashboard/templates/dashboard/new_admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>New User | User Dashboard</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    rel="stylesheet"><!-- Optional theme -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    rel="stylesheet"><!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-2'>
                <h3>Add a New User</h3>
            </div>
        </div>
        {% if messages %}
        <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'dashboard:create_admin' %}" method="post">
        {% csrf_token %}
            <table class='table_add'>
            {{ regform.as_table }}
            </table>
            <button class='btn btn-success btn-md' type='submit'>Create New User!</button>
        </form>
    </div>
</body>
</html>

user_dashboard/apps/dashboard/templates/dashboard/show.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>User Wall | User Dashboard</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
  	<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'dashboard:show' request.session.user_id %}">PROFILE<span class="sr-only">(current)</span></a></li>
      </ul>

     <ul class="nav navbar-nav navbar-right">
     	<li><a href="{% url 'login:index' %}">LOGOFF</a></li>
     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

  <div class='container'>
	  <div class='row'>
	  	<div class='col-md-6'><h3>{{user.first_name}} {{user.last_name}}</h3></div>
	  	{% if user.id == request.session.user_id %}
	  		<div class='col-md-3 col-md-offset-3'><h3><a href="{% url 'dashboard:edit' user.id %}">Edit Profile</a></h3></div>
	  	{% endif %}
	  </div>
	  <div class='row'>
		  <div class='col-md-2'><p>Registered at:</p></div>
		  <div class='col-md-2'><p>{{user.created_at}}</p></div>
	  </div>
	  <div class='row'>
	  	<div class='col-md-2'><p>User ID:</p></div>
	 	<div class='col-md-2'><p>#{{user.id}}</p></div>
	 </div>
	 <div class='row'>
	  	<div class='col-md-2'><p>Email address:</p></div>
	 	<div class='col-md-2'><p>{{user.email}}</p></div>
	 </div>
	  <div class='row'>
	  	<div class='col-md-2'><p>Description:</p></div>
	 	<div class='col-md-2'><p>{{user.description}}</p></div>
	 </div>
	 <div class='row'>
	  	<div class='col-md-2'><h4>New Message:</h4></div>
	 </div>
	 <div class='row'>
	  	<div class='col-md-6'>
	  	<form action="{% url 'dashboard:new_message' user.id %}" method="post">
	  		{% csrf_token %}
	  		<textarea name='message' class='form-control' rows='3'></textarea>
	  		<br>
	  		<button type='submit' class='btn btn-success btn-sm'>Submit</button>
  		</form>
  		</div>
	 </div>
	 <br>
	 {% for message in messages%}
		 <div class='row'>
		  	<div class='col-md-6'><p class='bg-primary wall_content'><strong>{{message.messageuser.first_name}} wrote:</strong></p></div>
		 </div>
		 <div class='row'>
		  	<div class='col-md-4'><p class='wall_content'>{{message.message}}</p></div>
		 </div>
	 {% for comment in comments %}
	  	{% if message.id == comment.message.id %}
	  	<div class='row'>
	  		<div class='col-md-5 col-md-offset-1'><p class='bg-success wall_content'><strong>{{comment.user.first_name}} wrote:</strong></p></div>
	 	</div>
	 	<div class='row'>
	  		<div class='col-md-4 col-md-offset-1'><p class='wall_content'>{{comment.comment}}</p></div>
	 	</div>
	 	{% endif %}
	{% endfor %}
	<div class='row'>
	  	<div class='col-md-5 col-md-offset-1'>
			<form action="{% url 'dashboard:new_comment' user.id message.id %}" method="post">
				{% csrf_token %}
			  	<textarea name='comment' class='form-control' rows='1'></textarea>
			  	<br>
		  		<button type='submit' class='btn btn-success btn-sm'>Submit</button>
			</form>
		</div>
	</div>
	<br>
  {% endfor %}
  </div>



</body>
</html>